# Generated by Django 5.2.1 on 2026-03-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='puede_ver_pagos',
            field=models.BooleanField(default=True, help_text='Si False, este administrador no podrá ver montos, saldos ni ingresos en el sistema de pagos', verbose_name='Puede ver información de pagos'),
        ),
    ]
