# Generated by Django 5.2.1 on 2026-03-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testimonio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonio',
            name='texto',
            field=models.TextField(help_text='Contá brevemente tu experiencia en Pilates Gravity (máximo 300 caracteres)', max_length=500, verbose_name='Comentario'),
        ),
    ]
