# Generated by Django 5.2.3 on 2025-09-23 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: '1 clase semanal', '2 clases semanales', etc.", max_length=100, verbose_name='Nombre del plan')),
                ('clases_por_semana', models.PositiveIntegerField(help_text='Cantidad de clases reservadas por semana', verbose_name='Clases por semana')),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio que debe pagar el cliente por mes', max_digits=10, verbose_name='Precio mensual')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del plan', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si este plan está disponible para asignar', verbose_name='Plan activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
                'ordering': ['clases_por_semana'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Reformer', 'Pilates Reformer'), ('Cadillac', 'Pilates Cadillac'), ('Especial', 'Clase Especial')], max_length=20, verbose_name='Tipo de clase')),
                ('nombre_personalizado', models.CharField(blank=True, help_text="Solo para clases especiales. Ejemplo: 'Pilates Prenatal', 'Clase de Rehabilitación', etc.", max_length=100, null=True, verbose_name='Nombre personalizado')),
                ('direccion', models.CharField(choices=[('sede_principal', 'Sede Principal - La Rioja 3044'), ('sede_2', 'Sede 2 - 9 de julio 3698')], default='sede_principal', help_text='Ubicación donde se dicta la clase', max_length=20, verbose_name='Sede')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10, verbose_name='Día de la semana')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('cupo_maximo', models.PositiveIntegerField(default=10, verbose_name='Cupo máximo')),
                ('activa', models.BooleanField(default=True, help_text='Las clases inactivas no aparecerán disponibles para reservar', verbose_name='Clase activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['direccion', 'dia', 'horario', 'tipo'],
                'permissions': [('can_manage_all_classes', 'Puede gestionar todas las clases')],
                'unique_together': {('tipo', 'dia', 'horario', 'direccion', 'nombre_personalizado')},
            },
        ),
        migrations.CreateModel(
            name='EstadoPagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_pago', models.DateField(blank=True, help_text='Fecha en que realizó su último pago', null=True, verbose_name='Fecha del último pago')),
                ('monto_ultimo_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto del último pago')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Positivo = crédito a favor, Negativo = deuda', max_digits=10, verbose_name='Saldo actual')),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas sobre el estado de pago del cliente', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Si el cliente está activo para el sistema de pagos', verbose_name='Estado activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('plan_actual', models.ForeignKey(blank=True, help_text='Plan de pago asignado según sus reservas activas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.planpago', verbose_name='Plan actual')),
            ],
            options={
                'verbose_name': 'Estado de Pago de Cliente',
                'verbose_name_plural': 'Estados de Pago de Clientes',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago', verbose_name='Fecha del pago')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Tipo de pago')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente de confirmación'), ('rechazado', 'Rechazado')], default='confirmado', max_length=20, verbose_name='Estado del pago')),
                ('concepto', models.CharField(help_text="Descripción del pago (ej: 'Pago mensual Enero 2025')", max_length=200, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este pago', verbose_name='Observaciones')),
                ('comprobante', models.CharField(blank=True, help_text='Número de recibo, transferencia, etc.', max_length=100, verbose_name='Número de comprobante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('registrado_por', models.ForeignKey(help_text='Administrador que registró este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Número de reserva')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activa', models.BooleanField(default=True, verbose_name='Reserva activa')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la reserva', verbose_name='Notas adicionales')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.clase', verbose_name='Clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_pilates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_reserva'],
                'permissions': [('can_manage_all_reservas', 'Puede gestionar todas las reservas'), ('can_view_all_reservas', 'Puede ver todas las reservas')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('usuario', 'clase'), name='unique_active_reservation_per_user_class')],
            },
        ),
    ]
