# Generated by Django 5.2.1 on 2026-01-28 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: '1 clase semanal', '2 clases semanales', etc.", max_length=100, verbose_name='Nombre del plan')),
                ('clases_por_semana', models.PositiveIntegerField(help_text='Cantidad de clases reservadas por semana', verbose_name='Clases por semana')),
                ('precio_mensual', models.DecimalField(decimal_places=2, help_text='Precio que debe pagar el cliente por mes', max_digits=10, verbose_name='Precio mensual')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del plan', verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, help_text='Si este plan está disponible para asignar', verbose_name='Plan activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('tipo_plan', models.CharField(choices=[('mensual', 'Plan Mensual Recurrente'), ('por_clase', 'Pago por Clase Individual')], default='mensual', help_text='Mensual: plan recurrente con pago mensual adelantado. Por clase: pago individual por clase.', max_length=20, verbose_name='Tipo de plan')),
                ('precio_por_clase', models.DecimalField(blank=True, decimal_places=2, help_text="Solo para planes tipo 'por_clase'. Precio que se cobra por cada clase individual.", max_digits=10, null=True, verbose_name='Precio por clase individual')),
            ],
            options={
                'verbose_name': 'Plan de Pago',
                'verbose_name_plural': 'Planes de Pago',
                'ordering': ['clases_por_semana'],
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Reformer', 'Pilates Reformer'), ('Cadillac', 'Pilates Cadillac'), ('Especial', 'Clase Especial')], max_length=20, verbose_name='Tipo de clase')),
                ('nombre_personalizado', models.CharField(blank=True, help_text="Solo para clases especiales. Ejemplo: 'Pilates Prenatal', 'Clase de Rehabilitación', etc.", max_length=100, null=True, verbose_name='Nombre personalizado')),
                ('direccion', models.CharField(choices=[('sede_principal', 'Sede Principal - La Rioja 3044'), ('sede_2', 'Sede 2 - 9 de julio 3696')], default='sede_principal', help_text='Ubicación donde se dicta la clase', max_length=20, verbose_name='Sede')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10, verbose_name='Día de la semana')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('cupo_maximo', models.PositiveIntegerField(default=10, verbose_name='Cupo máximo')),
                ('activa', models.BooleanField(default=True, help_text='Las clases inactivas no aparecerán disponibles para reservar', verbose_name='Clase activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['direccion', 'dia', 'horario', 'tipo'],
                'permissions': [('can_manage_all_classes', 'Puede gestionar todas las clases')],
                'unique_together': {('tipo', 'dia', 'horario', 'direccion', 'nombre_personalizado')},
            },
        ),
        migrations.CreateModel(
            name='EstadoPagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_pago', models.DateField(blank=True, help_text='Fecha en que realizó su último pago', null=True, verbose_name='Fecha del último pago')),
                ('monto_ultimo_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto del último pago')),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Positivo = crédito a favor, Negativo = deuda', max_digits=10, verbose_name='Saldo actual')),
                ('observaciones', models.TextField(blank=True, help_text='Notas internas sobre el estado de pago del cliente', verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, help_text='Si el cliente está activo para el sistema de pagos', verbose_name='Estado activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('ultimo_mes_cobrado', models.DateField(blank=True, help_text='Mes/año del último cobro mensual generado (formato: primer día del mes)', null=True, verbose_name='Último mes cobrado')),
                ('puede_reservar', models.BooleanField(default=True, help_text='Si el cliente puede reservar/modificar clases (False si tiene deuda vencida)', verbose_name='Puede reservar clases')),
                ('fecha_limite_pago', models.DateField(blank=True, help_text='Fecha límite para pagar sin restricciones (día 10 de cada mes)', null=True, verbose_name='Fecha límite de pago')),
                ('monto_deuda_mensual', models.DecimalField(decimal_places=2, default=0, help_text='Monto adeudado del mes actual', max_digits=10, verbose_name='Deuda mensual actual')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_pago', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('plan_actual', models.ForeignKey(blank=True, help_text='Plan de pago asignado según sus reservas activas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.planpago', verbose_name='Plan actual')),
            ],
            options={
                'verbose_name': 'Estado de Pago de Cliente',
                'verbose_name_plural': 'Estados de Pago de Clientes',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde cuando es válido este plan', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta cuando es válido este plan', verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True, help_text='Si este plan está activo para el usuario', verbose_name='Plan activo')),
                ('tipo_plan', models.CharField(choices=[('permanente', 'Plan Permanente'), ('temporal', 'Plan Temporal/Adicional')], default='permanente', help_text='Permanente se renueva automáticamente, temporal es de una sola vez', max_length=20, verbose_name='Tipo de plan')),
                ('renovacion_automatica', models.BooleanField(default=True, help_text='Si el plan se renueva automáticamente al vencer', verbose_name='Renovación automática')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre este plan específico', verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Administrador que asignó este plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.planpago', verbose_name='Plan de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_activos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Plan de Usuario',
                'verbose_name_plural': 'Planes de Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(help_text='Fecha en que se realizó el pago', verbose_name='Fecha del pago')),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Tipo de pago')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendiente', 'Pendiente de confirmación'), ('rechazado', 'Rechazado')], default='confirmado', max_length=20, verbose_name='Estado del pago')),
                ('concepto', models.CharField(help_text="Descripción del pago (ej: 'Pago mensual Enero 2025')", max_length=200, verbose_name='Concepto')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre este pago', verbose_name='Observaciones')),
                ('comprobante', models.CharField(blank=True, help_text='Número de recibo, transferencia, etc.', max_length=100, verbose_name='Número de comprobante')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('registrado_por', models.ForeignKey(help_text='Administrador que registró este pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reserva', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Número de reserva')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activa', models.BooleanField(default=True, verbose_name='Reserva activa')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre la reserva', verbose_name='Notas adicionales')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.clase', verbose_name='Clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_pilates', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DeudaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.DateField(help_text='Primer día del mes al que corresponde esta deuda', verbose_name='Mes/Año')),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Monto calculado según el plan (completo o medio mes)', max_digits=10, verbose_name='Monto original')),
                ('monto_pendiente', models.DecimalField(decimal_places=2, help_text='Monto que aún se debe (se reduce con pagos parciales)', max_digits=10, verbose_name='Monto pendiente')),
                ('es_medio_mes', models.BooleanField(default=False, help_text='Si se cobró medio mes por registrarse en segunda quincena', verbose_name='Es medio mes')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado completamente'), ('vencido', 'Vencido (después del día 10)'), ('parcial', 'Pagado parcialmente')], default='pendiente', max_length=20, verbose_name='Estado de la deuda')),
                ('fecha_vencimiento', models.DateField(help_text='Día 10 del mes correspondiente', verbose_name='Fecha de vencimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_mensuales', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('plan_aplicado', models.ForeignKey(help_text='Plan que se usó para calcular esta deuda', on_delete=django.db.models.deletion.CASCADE, to='gravity.planpago', verbose_name='Plan aplicado')),
            ],
            options={
                'verbose_name': 'Deuda Mensual',
                'verbose_name_plural': 'Deudas Mensuales',
                'ordering': ['-mes_año'],
                'unique_together': {('usuario', 'mes_año')},
            },
        ),
    ]
