# Generated by Django 5.2.3 on 2025-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clase',
            name='nombre_personalizado',
            field=models.CharField(blank=True, help_text="Solo para clases especiales. Ejemplo: 'Pilates Prenatal', 'Clase de Rehabilitación', etc.", max_length=100, null=True, verbose_name='Nombre personalizado'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10, verbose_name='Día de la semana'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='tipo',
            field=models.CharField(choices=[('Reformer', 'Pilates Reformer'), ('Cadillac', 'Pilates Cadillac'), ('Especial', 'Clase Especial')], max_length=20, verbose_name='Tipo de clase'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('tipo', 'dia', 'horario', 'nombre_personalizado')},
        ),
    ]
