# Generated by Django 5.2.1 on 2026-03-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha específica en que el cliente no asistirá', verbose_name='Fecha de ausencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias_temporales', to='gravity.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Ausencia Temporal',
                'verbose_name_plural': 'Ausencias Temporales',
                'ordering': ['-fecha'],
                'unique_together': {('reserva', 'fecha')},
            },
        ),
    ]
