# Generated by Django 5.2.3 on 2025-10-24 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha desde cuando es válido este plan', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(help_text='Fecha hasta cuando es válido este plan', verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=True, help_text='Si este plan está activo para el usuario', verbose_name='Plan activo')),
                ('tipo_plan', models.CharField(choices=[('permanente', 'Plan Permanente'), ('temporal', 'Plan Temporal/Adicional')], default='permanente', help_text='Permanente se renueva automáticamente, temporal es de una sola vez', max_length=20, verbose_name='Tipo de plan')),
                ('renovacion_automatica', models.BooleanField(default=True, help_text='Si el plan se renueva automáticamente al vencer', verbose_name='Renovación automática')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre este plan específico', verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Plan de Usuario',
                'verbose_name_plural': 'Planes de Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_active_reservation_per_user_class',
        ),
        migrations.AddField(
            model_name='planusuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que asignó este plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='planusuario',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.planpago', verbose_name='Plan de pago'),
        ),
        migrations.AddField(
            model_name='planusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_activos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
