# Generated by Django 5.2.3 on 2025-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_alter_clase_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase',
            options={'ordering': ['direccion', 'dia', 'horario', 'tipo'], 'permissions': [('can_manage_all_classes', 'Puede gestionar todas las clases')], 'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clase',
            name='direccion',
            field=models.CharField(choices=[('sede_principal', 'Sede Principal - La Rioja 3044'), ('sede_2', 'Sede 2 - 9 de julio 3698')], default='sede_principal', help_text='Ubicación donde se dicta la clase', max_length=20, verbose_name='Sede'),
        ),
        migrations.AlterUniqueTogether(
            name='clase',
            unique_together={('tipo', 'dia', 'horario', 'direccion', 'nombre_personalizado')},
        ),
    ]
