# Generated by Django 5.2.1 on 2026-03-03 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0002_ausenciatemporal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('permanente', 'Cancelación permanente'), ('temporal', 'Ausencia temporal')], max_length=20, verbose_name='Tipo de cancelación')),
                ('fecha_ausencia', models.DateField(blank=True, help_text='Solo para cancelaciones temporales', null=True, verbose_name='Fecha de ausencia')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de notificación')),
                ('leida_por', models.ManyToManyField(blank=True, related_name='notificaciones_leidas', to=settings.AUTH_USER_MODEL, verbose_name='Vista por')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cancelacion', to='gravity.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Notificación de Cancelación',
                'verbose_name_plural': 'Notificaciones de Cancelaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
