# Generated by Django 5.2.1 on 2026-03-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0003_notificacioncancelacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planusuario',
            name='fecha_cancelacion_reservas',
            field=models.DateField(blank=True, help_text='Fecha en que el cron debe cancelar las reservas de este plan', null=True, verbose_name='Fecha de cancelación de reservas'),
        ),
        migrations.AddField(
            model_name='planusuario',
            name='reservas_canceladas',
            field=models.BooleanField(default=False, help_text='True si el cron ya procesó la cancelación de reservas de este plan', verbose_name='Reservas canceladas'),
        ),
    ]
