# Generated by Django 5.2.1 on 2026-04-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0005_notificacioncancelacionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='es_recupero',
            field=models.BooleanField(default=False, help_text='Reserva de recupero por ausencia propia. No cuenta para el límite semanal del plan.', verbose_name='Es recupero'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_unica',
            field=models.DateField(blank=True, help_text='Para recuperos y cupos temporales. Se cancela automáticamente al día siguiente de esta fecha.', null=True, verbose_name='Fecha única'),
        ),
    ]
