# Generated by Django 5.2.1 on 2026-04-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0006_reserva_es_recupero_reserva_fecha_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciatemporal',
            name='notificacion_vencimiento_vista',
            field=models.BooleanField(default=False, help_text='True cuando el usuario ya vio el aviso de que perdió el plazo de recupero', verbose_name='Notificación de vencimiento vista'),
        ),
    ]
