# Generated by Django 5.2.1 on 2026-04-15 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0007_ausenciatemporal_notificacion_vencimiento_vista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteDeudaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto original anterior')),
                ('monto_ajustado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ajustado')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del ajuste')),
                ('fecha_ajuste', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del ajuste')),
                ('admin_que_ajusto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='gravity.deudamensual', verbose_name='Deuda ajustada')),
                ('usuario_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_deuda', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ajuste de Deuda Especial',
                'verbose_name_plural': 'Ajustes de Deudas Especiales',
                'ordering': ['-fecha_ajuste'],
            },
        ),
    ]
