# Generated by Django 5.2.1 on 2026-04-23 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0008_ajustedeudaespecial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPlanAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('leida_por', models.ManyToManyField(blank=True, related_name='notificaciones_plan_adicional_leidas', to=settings.AUTH_USER_MODEL, verbose_name='Vista por')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gravity.planpago', verbose_name='Plan agregado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_plan_adicional', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Plan Adicional',
                'verbose_name_plural': 'Notificaciones de Planes Adicionales',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
