# Generated by Django 5.2.1 on 2026-05-07 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0009_notificacionplanadicional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, verbose_name='Motivo')),
                ('motivo_detalle', models.TextField(blank=True, verbose_name='Detalle del motivo')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email enviado al usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cancelación')),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones_admin', to='gravity.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Cancelación por Administrador',
                'verbose_name_plural': 'Cancelaciones por Administrador',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
