# Generated by Django 5.2.1 on 2026-07-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0011_inasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambioPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('plan_actual', models.ForeignKey(blank=True, help_text='Plan que tenía el usuario al solicitar el cambio (vacío si no tenía ninguno)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_plan_actual', to='gravity.planpago', verbose_name='Plan actual')),
                ('plan_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_como_plan_solicitado', to='gravity.planpago', verbose_name='Plan solicitado')),
                ('reservas_a_cancelar', models.ManyToManyField(blank=True, help_text='Reservas que el usuario eligió ceder por bajar a un plan con menos clases por semana', related_name='solicitudes_cambio_plan', to='gravity.reserva', verbose_name='Reservas a cancelar')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_plan_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cambio_plan', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Plan',
                'verbose_name_plural': 'Solicitudes de Cambio de Plan',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
