# Generated by Django 5.2.1 on 2026-09-05 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0012_solicitudcambioplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('correccion_saldo', 'Corrección de saldo'), ('pago_editado', 'Pago corregido'), ('pago_anulado', 'Pago anulado'), ('pago_registrado', 'Pago registrado'), ('cuota_ajustada', 'Cuota ajustada'), ('cuota_creada', 'Cuota generada manualmente'), ('cuota_eliminada', 'Cuota eliminada'), ('recalculo', 'Recálculo de la cuenta')], default='correccion_saldo', max_length=30, verbose_name='Tipo de corrección')),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text="Positivo = suma crédito a favor. Negativo = quita crédito o agrega deuda. Solo se computa en el saldo si el tipo es 'Corrección de saldo'.", max_digits=10, verbose_name='Impacto en el saldo')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Qué se hizo')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo indicado por el administrador')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo antes')),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo después')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la corrección')),
                ('admin_que_ajusto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_saldo', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Corrección de cuenta',
                'verbose_name_plural': 'Correcciones de cuenta',
                'ordering': ['-fecha'],
            },
        ),
    ]
