# Generated by Django 5.2.1 on 2026-09-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0013_ajustesaldo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteHorarioProfesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('extra', 'Turno extra'), ('reemplazo', 'Trabajó en otro horario'), ('ausencia', 'No trabajó')], max_length=15, verbose_name='Tipo de ajuste')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('sede', models.CharField(blank=True, choices=[('sede_principal', 'Sede Principal - La Rioja 3044'), ('sede_2', 'Sede 2 - 9 de julio 3696')], max_length=20, verbose_name='Sede')),
                ('motivo', models.CharField(blank=True, help_text='Reemplazo de una compañera, feriado, salió antes, etc.', max_length=200, verbose_name='Motivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_horario', to=settings.AUTH_USER_MODEL, verbose_name='Profesora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_horario_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Ajuste de horario de profesora',
                'verbose_name_plural': 'Ajustes de horario de profesoras',
                'ordering': ['-fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueHorarioProfesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10, verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de entrada')),
                ('hora_fin', models.TimeField(verbose_name='Hora de salida')),
                ('sede', models.CharField(choices=[('sede_principal', 'Sede Principal - La Rioja 3044'), ('sede_2', 'Sede 2 - 9 de julio 3696')], default='sede_principal', max_length=20, verbose_name='Sede')),
                ('vigente_desde', models.DateField(help_text='Fecha a partir de la cual la profesora cumple este horario', verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Último día en que rigió este horario. Vacío significa que sigue vigente.', null=True, verbose_name='Vigente hasta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloques_horario_creados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques_horario', to=settings.AUTH_USER_MODEL, verbose_name='Profesora')),
            ],
            options={
                'verbose_name': 'Bloque de horario de profesora',
                'verbose_name_plural': 'Bloques de horario de profesoras',
                'ordering': ['profesora', 'dia', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ValorHoraProfesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, help_text='Monto en pesos que cobra la profesora por cada hora trabajada', max_digits=10, verbose_name='Valor por hora')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('vigente_hasta', models.DateField(blank=True, help_text='Vacío significa que es el valor actual', null=True, verbose_name='Vigente hasta')),
                ('observaciones', models.CharField(blank=True, help_text='Motivo del cambio (aumento, acuerdo, etc.)', max_length=200, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_hora', to=settings.AUTH_USER_MODEL, verbose_name='Profesora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_hora_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Valor hora de profesora',
                'verbose_name_plural': 'Valores hora de profesoras',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionProfesora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_año', models.DateField(help_text='Primer día del mes que se está pagando', verbose_name='Mes liquidado')),
                ('horas_liquidadas', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Horas trabajadas')),
                ('monto_calculado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto calculado por el sistema')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto efectivamente pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('observaciones', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('profesora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to=settings.AUTH_USER_MODEL, verbose_name='Profesora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Liquidación de profesora',
                'verbose_name_plural': 'Liquidaciones de profesoras',
                'ordering': ['-mes_año'],
                'unique_together': {('profesora', 'mes_año')},
            },
        ),
    ]
