# Generated by Django 5.2.1 on 2026-09-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0014_ajustehorarioprofesora_bloquehorarioprofesora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustehorarioprofesora',
            name='bloque',
            field=models.ForeignKey(blank=True, help_text='Turno del horario semanal al que se le aplica el cambio. Vacío significa que el cambio vale para todo el día.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ajustes', to='gravity.bloquehorarioprofesora', verbose_name='Turno afectado'),
        ),
        migrations.AddField(
            model_name='ajustehorarioprofesora',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_puntuales_profesoras', to='gravity.clase', verbose_name='Clase que dicta'),
        ),
        migrations.AddField(
            model_name='bloquehorarioprofesora',
            name='clase',
            field=models.ForeignKey(blank=True, help_text='Clase del sistema de la que salió este turno, si se cargó eligiéndola', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_profesoras', to='gravity.clase', verbose_name='Clase que dicta'),
        ),
    ]
