# Generated by Django 5.2.1 on 2026-10-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0015_ajustehorarioprofesora_bloque_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Quién creó la reserva: el propio alumno o el administrador que la cargó', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('fecha_unica__isnull', True)), fields=('usuario', 'clase'), name='unique_reserva_permanente_activa'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True), ('fecha_unica__isnull', False)), fields=('usuario', 'clase', 'fecha_unica'), name='unique_reserva_fecha_unica_activa'),
        ),
    ]
